services:
  postgres:
    image: postgres:16-alpine
    container_name: db_postgres
    environment:
      POSTGRES_DB: api_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: spring_api
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/api_backend
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345678
    ports:
      - "8080:8080"
    volumes:
      - uploads:/app/uploads   # persistir archivos subidos

volumes:
  pgdata:
  uploads: