services:
  api:
    build: .
    container_name: spring_api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-soft-rice-b8mef59h-pooler.c-14.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      SPRING_DATASOURCE_USERNAME: neondb_owner
      SPRING_DATASOURCE_PASSWORD: npg_9kGDKMmCS2uj
      JWT_SECRET: EstaEsUnaClaveSecretaLargaParaMiApiBackend2026
    ports:
      - "8080:8080"
    volumes:
      - uploads:/app/uploads

volumes:
  uploads: